### ISSUE TITLE
Script breaking Windows Update

### ISSUE THREAD

**Issue by lucasdeeiroz** [teeotsa/windows-11-debloat#1]
After running script I'm not able to run updates on Windows 11.

First, Windows Update gives me an error when I search for updates. After enabling Windows Update through script, Windows Update finds new updates, but it is not able to install the latest Cumulative Update for Windows.

Also, the script uninstall Microsoft Store by default, which I really think shouldn't be that way.

**Comment by teeotsa** [comment]
Thanks for informing me. 

About the Microsoft Store, you can head to bin folder and find file named 'bloatware_list.txt' and edit it. (Comment out NET runtimes + Windows Store package) (Ima do it later)
![Step1](https://user-images.githubusercontent.com/78772453/137641678-f4bae608-ba29-4e91-ad36-a843ee8e6b8d.PNG)

![Step2](https://user-images.githubusercontent.com/78772453/137641685-6f053e8a-bc84-4a5a-9d68-e466b1f7f22a.PNG)

![Step3](https://user-images.githubusercontent.com/78772453/137641686-77723506-702b-4e11-a05a-94c2ad384838.PNG)


And about the updates, ima check out tomorrow. Maybe try to press "Enable Windows Update" and try to search for updates again!
![Update](https://user-images.githubusercontent.com/78772453/137641513-3b079a62-479d-4e3c-bbc1-9798b7512906.PNG)


Thanks for starring this repository, much appreciated 😃

**Comment by lucasdeeiroz** [comment]
Fixed! Thanks, nice project!
