### ISSUE TITLE
Script don't dele provisionned Package

### ISSUE THREAD

**Issue by V1ce** [teeotsa/windows-11-debloat#10]
Hi,

I post for suggest to also remove provisionned packages in the script. I use this script for prepare reference machine and after the sysprep execution the default user reinstall all bloatware so this make this script usless.  

I have tested to add this at line 1042 and sysprep the machine and i get a clean profile : 

Get-AppxProvisionedPackage -Online | Where-Object DisplayName -like $Bloat | Remove-AppxProvisionedPackage -Online

Thanks

**Comment by teeotsa** [comment]
Hey, 

Thank you for your suggestion! You could just make a pull request next time haha.

Have a nice day!

https://github.com/teeotsa/windows-11-debloat/commit/dc236a8c2607f2cfff67eb6d7ef8d2e60cc64dbd

**Comment by V1ce** [comment]
Yes sorry im not familiar with this. thanks for the modification. Bye
