### ISSUE TITLE
Cannot re-download from Microsoft Store Afterwards

### ISSUE THREAD

**Issue by edmondt** [teeotsa/windows-11-debloat#11]
I did the tweak and debloat on Windows 11, but want to re-download Mail, Alarm, Camera etc. Went to the Microsoft Store, was able to download Mail, but cannot download other apps. Also no purchased apps can be downloaded after.

May I ask which service I need to re-enable to be able to download? I like the tweaks, just need to be able to get back a few things and use the Store.

**Comment by teeotsa** [comment]
Hey, i'm sorry for the problems i've caused.

Try to use "Restore Tweaks" button and maybe reset OOSHUTUP10 settings to default. Later you can "re-tweak" your system!

These scheduled tasks probably caused the problem
```
"\Microsoft\Windows\PushToInstall\LoginCheck"
"\Microsoft\Windows\PushToInstall\Registration"
```

**Comment by edmondt** [comment]
I didn't the restore tweaks but it didn't work even after a reboot. Thankful your script created a system restore and that works... 

I'm going to look for those schedule tasks again and see if it works :)

**Comment by teeotsa** [comment]
> I didn't the restore tweaks but it didn't work even after a reboot. Thankful your script created a system restore and that works...
> 
> I'm going to look for those schedule tasks again and see if it works :)


Okay, I'm glad the restore point worked out for you :smiley: 

If you find something, feel free to let me know. I'd really appreciate that.

:) hehe
