### ISSUE TITLE
Need a Wiki for what each script can do

### ISSUE THREAD

**Issue by pratyush-1327** [teeotsa/windows-11-debloat#12]
some tweaks are confusing, dont know what they will remove or tweak . For ex. ownership and essential
Pls create a wiki about what does essential tweaks do.

**Comment by teeotsa** [comment]
Hey @pratyush-1327,

Thank you for suggesting that, i'll certainly try to add Wiki to this project!



> For ex. ownership and essential

Take Ownership adds context menu item, that allows you to basically delete any system files you'd ever want to!

**Comment by pratyush-1327** [comment]
@teeotsa welcome!
For the mean time , i can just see the files what they do.
Thanks for taking this in consideration.
