### ISSUE TITLE
Remove Bloatware stuck on removing SpeechToTextOverlay

### ISSUE THREAD

**Issue by MagTheDev** [teeotsa/windows-11-debloat#13]
The script gets stuck at Trying to remove "Microsoft.XboxSpeechToTextOverlay" Package! Be patient...
I've been running it for 30mins. with no progress. Note that none of the preinstalled app were removed
Restarting the script + pc didnt work

![image](https://user-images.githubusercontent.com/49731971/150639805-495e3286-3419-4b46-9a0b-b3ed5e0870c7.png)

**Comment by teeotsa** [comment]
Hey, 

I'm sorry to hear that, maybe comment out "Microsoft.XboxSpeechToTextOverlay"?

**Comment by MagTheDev** [comment]
Thanks, i will follow up tomorrow as i dont have access to the pc now
