### ISSUE TITLE
"see which apps are affecting your battery life"

### ISSUE THREAD

**Issue by techjune** [teeotsa/windows-11-debloat#14]
Thank you for your hard work.

Just one thing please.

I don't see which apps are affecting your battery lifein power options after debloat.

I asked if it could be modified so that only this part could be used.

**Comment by teeotsa** [comment]
Hey, thank you!

Try to enable hibernation [You can find the script here](https://github.com/teeotsa/windows-11-debloat/blob/main/restoreScripts/enableHibernation.ps1)

**Comment by teeotsa** [comment]
Please re-open this issue if you have any issues!
