### ISSUE TITLE
Some important service disabled for enterprise use + new bloatware list

### ISSUE THREAD

**Issue by V1ce** [teeotsa/windows-11-debloat#18]
Hi,

I want to suggest to not disable some service because its can make the system unstable and get random error for a network use and pc administration.

i suggest to let these service active , i think this not take ressources as much and some of them are running only if the system needed for a task and some are clearly essential like the print spooler or remote desktop services ! Its look like a blindly disable, pls take care about that :

#Usefull for pc administration
"RemoteRegistry" 

#Usefull for RDP

"UmRdpService" 
"TermService" 
"SessionEnv" 
"RasMan" 
"RasAuto" 

#Essential.....
"Spooler" 
"PrintNotify"

#Maybe usefull for event viewer etc... 

"WdiSystemHost" 
"WdiServiceHost" 
"DPS" 
"diagsvc" 
"WerSvc" 

#Other, we don't know if can make system unstable for some use
"svsvc"
"fhsvc" 
"Fax"

Second thing i noticed that the bloatware list is now pretty small, a reason for this?

I suggest this for an enterprise use, maybe some apps like xbox can be commented for a personnel and gamer use. Maybe its can be usefull to make a bloatware remove function for personnal and enterpise use ( for a very clean system), maybe ill take a time for help at this : 

        "Microsoft.BioEnrollment"
        "Microsoft.LockApp"
        "Microsoft.MicrosoftEdgeDevToolsClient"
        #"Microsoft.MicrosoftEdge"
        "Microsoft.BingNews"
        "Microsoft.BingWeather"
        "Microsoft.GetHelp"
        "Microsoft.Getstarted"
        "Microsoft.MicrosoftOfficeHub"
        "Microsoft.MicrosoftSolitaireCollection"
        "Microsoft.MicrosoftStickyNotes" # its make sysprep fail
        "Microsoft.People"
        "Microsoft.PowerAutomateDesktop"
        "Microsoft.SecHealthUI"
        "Microsoft.Todos"
        #"Microsoft.Windows.Photos" 
        "Microsoft.WindowsAlarms"
        #"Microsoft.WindowsCamera" # Maybe usefull for test a webcam 
        "microsoft.windowscommunicationsapps"
        "Microsoft.WindowsFeedbackHub"
        "Microsoft.WindowsMaps"
        #"Microsoft.WindowsSoundRecorder" Maybe usefull for test a micro
        "Microsoft.YourPhone"
        "Microsoft.ZuneMusic"
        "Microsoft.ZuneVideo"
        "MicrosoftTeams"
        "Microsoft.549981C3F5F10" # cortana
        "Microsoft.GamingApp"
        "Microsoft.Xbox.TCUI"
        "Microsoft.XboxApp"
        "Microsoft.XboxGameOverlay"
        "Microsoft.XboxGamingOverlay"
        "Microsoft.XboxIdentityProvider"
        "Microsoft.XboxSpeechToTextOverlay"
        "MicrosoftWindows.Client.WebExperience"

Thanks

**Comment by teeotsa** [comment]
Hey,

Well, I can comment out most of those services! 

Now, about bloatware packages. I can't remove most of them, some break Xbox/Windows Store, some break regular Windows usage. And bio enrollment is needed for pin code logins and such.

Diagnostic services won't really affect Event Viewer AFAIK (Correct me I'm wrong :joy: ).

I will leave Error Reporting disabled! (Won't change anything about it).

Everything you mentioned except Diagnostics and Error Reporting were commented out. And no, it isn't "blindly disabled".

Thank you anyways! Next time you can just create a pull request. :joy: 

https://github.com/teeotsa/windows-11-debloat/commit/ad7d78731042aff6cfb135f6f94dca589f57aa32
