### ISSUE TITLE
Some settings get disabled by "Essential tweaks"

### ISSUE THREAD

**Issue by KalaRaja** [teeotsa/windows-11-debloat#22]
After applying essential tweaks, Some settings are disabled and a following message is shown:

"some of these settings are managed by your organization"

**Comment by KalaRaja** [comment]
> Oh, that's normal. What are you trying to change ?

Cannot change lockscreen settings, like lockscreen wallpaper, quick status etc.

**Comment by teeotsa** [comment]
> > Oh, that's normal. What are you trying to change ?
> 
> Cannot change lockscreen settings, like lockscreen wallpaper, quick status etc.

Oh, I'm sorry.

Run this line of code to get lockscreen customization back. 
```powershell
Remove-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization" -Name "NoLockScreen" -ErrorAction SilentlyContinue
```
Anything else I can do for you ? :)

**Comment by teeotsa** [comment]
> thanks, are you going to include this in the main script?

No problem ! 

Well, I'll try my best to re-design everything and maybe then . Right now, no .

**Comment by KalaRaja** [comment]
> > thanks, are you going to include this in the main script?
> 
> No problem !
> 
> Well, I'll try my best to re-design everything and maybe then . Right now, no .

cool, thanks. I like how light weight the script is.

**Comment by teeotsa** [comment]
> cool, thanks. I like how light weight the script is.

Haha, thanks. It's not :flushed: could be better .
