### ISSUE TITLE
Little tweaks to (maybe) add.. ^-^

### ISSUE THREAD

**Issue by Yumekonoi** [teeotsa/windows-11-debloat#28]
Hi! I hope this does not bother you!
I use for work a little bat that i made that, besides other things, removes widget, chat from the task bar and trasition Start to the left. 
I didn't find a way to make it for the machine, only for the user but it can be usefull if u want to do it in second c:

Here is: 
rem -------------------------   Disable "Widget Icon on TaskBar"
REG ADD HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced		/v TaskbarDa /t REG_DWORD /d 0 /f
rem -------------------------    Disable "Chat Icon on TaskBar"
REG ADD HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced		/v TaskbarMn /t REG_DWORD /d 0 /f
rem -------------------------   Enable "Windows Start on Left" 
REG ADD HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced		/v TaskbarAl /t REG_DWORD /d 0 /f

Thank you for reading! Have a nice day :)

**Comment by teeotsa** [comment]
Hey! 

> I didn't find a way to make it for the machine, only for the user but it can be usefull if u want to do it in second c:

Use HKLM instead of HKCU, like so :
```batch
rem ------------------------- Disable "Widget Icon on TaskBar"
REG ADD HKLM\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced /v TaskbarDa /t REG_DWORD /d 0 /f
rem ------------------------- Disable "Chat Icon on TaskBar"
REG ADD HKLM\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced /v TaskbarMn /t REG_DWORD /d 0 /f
rem ------------------------- Enable "Windows Start on Left"
REG ADD HKLM\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced /v TaskbarAl /t REG_DWORD /d 0 /f
```

Thank you for your contribution 😃 Have a nice day :)

https://github.com/teeotsa/windows-11-debloat/commit/73bcb03481672e902f26f28be141e1870a991f25

**Comment by Yumekonoi** [comment]
I already tried in the past but for not have a doubt I tried right now and it dont work with a new user. Even in audit mode. Maybe I'm doing something wrong, is it possible. Anyways thank you for your suggestion! 😸

**Comment by teeotsa** [comment]
Make sure you have those values deleted in Current User hive :) Should work.

If you have any issues, hit me up on Discord. 

Teeotsa#6167
