### ISSUE TITLE
No more Defender notifications

### ISSUE THREAD

**Issue by Niecks90** [teeotsa/windows-11-debloat#3]
After i applied the script and re-enable manually Defender, real time portection works well but i don't have any notifications about Windows Security.

I checked everywhere, no GPO, no REG, notifications are activated in Windows Security

**Comment by teeotsa** [comment]
```
Remove-ItemProperty -Path "HKCU:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\PushNotifications" -Name "NoTileApplicationNotification" -Force | Out-Null
if (!(Test-Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings")){
    New-Item -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings" -Force | Out-Null
}
Get-ChildItem -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings" | foreach {
    Set-ItemProperty -Path $_.PsPath -Name "Enabled" -Type DWord -Value 1
}
 should fix it
```
This will fix it :smile:

**Comment by Niecks90** [comment]
Fix worked 👌. Thanks for your help 
![image](https://user-images.githubusercontent.com/93446974/139554231-da3b1eec-6345-4750-a73c-1658460f0298.png)
