### ISSUE TITLE
Search doesnt work, even after restore scrips

### ISSUE THREAD

**Issue by ZVLIAN** [teeotsa/windows-11-debloat#30]
![image](https://github.com/teeotsa/windows-11-debloat/assets/116763542/45eecaef-1a43-4101-b488-7e3c3d4d3e12)

Please tell me how to stop the script from suspending the searchhost process

**Comment by teeotsa** [comment]
Hey.

Well, just ran the script and everything works perfectly fine. 

Latest Windows 11 build.

You ran any other scripts?

![image](https://github.com/teeotsa/windows-11-debloat/assets/78772453/a94fa11b-4bee-4cb7-967a-62dd22a31082)

**Comment by ZVLIAN** [comment]
Oh sorry, I was talking about web results, I was able to get them back
manually via the registry, but It would be great if you could include a way
of restoring those in a script


Teeotsa ***@***.***> schrieb am Mi., 26. Juli 2023, 04:30:

**Comment by teeotsa** [comment]
Will do
