### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by k3v1nwrld** [teeotsa/windows-11-debloat#4]
Was basically wondering what do i need to remove from the script to not disable search?

**Comment by teeotsa** [comment]
Hello! You can use **Restore Scripts** to restore Windows Search functionality. Restore scripts are located in Debloater's folder or you can find them [here!](https://github.com/teeotsa/windows-11-debloat/tree/main/restoreScripts)

# You have to edit out these parts of the code
![powershell_ise_3nfYkCY6lj](https://user-images.githubusercontent.com/78772453/140657077-83157fc6-5f56-45f2-afb0-8f8b3de6459d.png)
![powershell_ise_jkA1h0Y7jd](https://user-images.githubusercontent.com/78772453/140657084-c7a7e36c-460c-41a2-9edc-111880ac00c9.png)

If you still experience problems, please let me know :smiley:
