### ISSUE TITLE
Wifi network doesn't work

### ISSUE THREAD

**Issue by happylamp99** [teeotsa/windows-11-debloat#5]
Can't connect to my wifi network, "Network security key isn't correct" I'm sure it's not the case, I tried running restoreWifi, reboot,still, doesn't work,tried disabling re enabling device, doesn't work, if I unplug and plug the wifi adapter, it will connect WITH internet access, however it displays no connection icon with no internet and in the available networks page it says connected secured,weird.

**Comment by teeotsa** [comment]
Hello

It shouldn't be from the script. I have to try tho, i'll let you know

Mean time, you can restart your netword device or use restore point
