### ISSUE TITLE
I can't type anything in any windows tab

### ISSUE THREAD

**Issue by VecxDw** [teeotsa/windows-11-debloat#7]
hello i just reinstalled windows 11 i just debloated it, now i can't even write anything in the windows search engine or in the settings.

Pls i need help

![image](https://user-images.githubusercontent.com/59230314/141603046-ef0ca7d6-5d0d-46cf-bddc-a5bb6e2b1c33.png)

**Comment by teeotsa** [comment]
Hello! Im so sorry about what happend to you

You need to start TabletInputService and change it to automatic!

I made script which auto starts the service
```
If (!([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]'Administrator')) {
	Start-Process powershell.exe "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -Verb RunAs
	Exit
}
New-Item -Path "$env:SystemRoot\StartService.bat" -ItemType File -Value "
sc start TabletInputService
" -Force -ErrorAction SilentlyContinue | Out-Null

$StartupFolder = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run";
If(!(Test-Path $StartupFolder)){
    New-Item -Path $StartupFolder -Force | Out-Null
}
Set-ItemProperty -Path $StartupFolder -Name StartTabletInputService -Value "$env:SystemRoot\StartService.bat"
```

Contact me via Discord (Teeotsa#6167) if you have any more problems :wink:
