### ISSUE TITLE
Delay to open windows start menu 

### ISSUE THREAD

**Issue by Isaakk** [teeotsa/windows-11-debloat#8]
Hello I just debloated win 11 with ur tool and seems that now the Start menu is taking 1-3 second delay to show up, I think it is cause I disabled cortana but I cannot enable it again because the button of the script don't do anything, it can be too because I disabled action center but enabled it again.

edit: also the internet status icon on the notification tray is always "identifying..."
edit2: reformated the pc and did the whole thing but this time without the disable cortana and action center, the "identifying..." thing is still there but start menu is working good, so prob some "essential tweaks" is causing the "identifying..." 

Thanks for the tool.

**Comment by teeotsa** [comment]
Hello there! :smiley: Thank you for your amazing words :star_struck: 

Here is the script to enable Cortana. Paste it into PowerShell : 
```
Remove-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Personalization\Settings" -Name "AcceptedPrivacyPolicy" -ErrorAction SilentlyContinue
If (!(Test-Path "HKCU:\SOFTWARE\Microsoft\InputPersonalization\TrainedDataStore")) {
New-Item -Path "HKCU:\SOFTWARE\Microsoft\InputPersonalization\TrainedDataStore" -Force | Out-Null
}
Set-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\InputPersonalization" -Name "RestrictImplicitTextCollection" -Type DWord -Value 0
Set-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\InputPersonalization" -Name "RestrictImplicitInkCollection" -Type DWord -Value 0
Remove-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\InputPersonalization\TrainedDataStore" -Name "HarvestContacts" -ErrorAction SilentlyContinue
Remove-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search" -Name "AllowCortana" -ErrorAction SilentlyContinue
Set-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Search" -Name "BingSearchEnabled" -Type DWord -Value "1"
Remove-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Search" -Name "CortanaConsent" -ErrorAction SilentlyContinue
Remove-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search" -Name "DisableWebSearch" -ErrorAction SilentlyContinue
Set-Service "WSearch" -StartupType Automatic
Start-Service "WSearch" -WarningAction SilentlyContinue
Set-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Search" -Name "SearchboxTaskbarMode" -Type DWord -Value 1
```

**Comment by teeotsa** [comment]
This issue will be closed in 5 days if there is no replies!

**Comment by teeotsa** [comment]
Hey! Run [this script here](https://github.com/teeotsa/windows-11-debloat/blob/main/restoreScripts/restoreScheduledTasks.ps1) to fix the "indentifying..." problem! Let me know if this works for you!

**Comment by Isaakk** [comment]
Hello, unfortunately it didn't work, but I noticed that the icon refresh when I restart the windows explorer, but not anymore after that.

Cheers

**Comment by teeotsa** [comment]
Maybe this will work? 
```
Set-Service -Name iphlpsvc -StartupType Automatic
Start-Service -Name iphlpsvc
Set-Service -Name WwanSvc -StartupType Automatic
Start-Service -Name WwanSvc
Set-Service -Name WlanSvc -StartupType Automatic 
Start-Service -Name WlanSvc
Set-Service -Name dot3svc -StartupType Automatic
Start-Service -Name dot3svc
Enable-ScheduledTask -TaskName "\Microsoft\Windows\NetTrace\GatherNetworkInfo" | Out-Null
Enable-ScheduledTask -TaskName "\Microsoft\Windows\NlaSvc\WiFiTask" | Out-Null
Enable-ScheduledTask -TaskName "\Microsoft\Windows\SoftwareProtectionPlatform\SvcRestartTaskNetwork"  | Out-Null
Enable-ScheduledTask -TaskName "\Microsoft\Windows\WDI\ResolutionHost" | Out-Null
```

**Comment by Isaakk** [comment]
It didn't, the icon just refreshed 1 time when I run the script but after that it's the same, it won't refresh if I disable the adapter for example.

**Comment by teeotsa** [comment]
> It didn't, the icon just refreshed 1 time when I run the script but after that it's the same, it won't refresh if I disable the adapter for example.

I don't know then, right now i don't have time to deal with this. Can't you just use Restore Point. Im really sorry!

And you can edit the script and tweak it as you wish :smiley: 

Im sorry

**Comment by Isaakk** [comment]
No problem, is not a big deal, wifitask etc its know to cause some problems so its ok to have it off. If I don't have internet ill know it anyways.

**Comment by MLXProjects** [comment]
New info, not sure if needed but still:
On event viewer, this seems to log when clicking the start button (translated from spanish, may not be exactly accurate)
```Cannot start DCOM server: MicrosoftWindows.Client.CBS_1000.22000.708.0_x64__cw5n1h2txyewy!CortanaUI as Unavailable/Unavailable.
Error "2147942402" while starting this command:
"C:\Windows\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\SearchHost.exe" -ServerName:CortanaUI.AppXstmwaab17q5s3y22tp6apqz7a45vwv65.mca```

**Comment by teeotsa** [comment]
> New info, not sure if needed but still: On event viewer, this seems to log when clicking the start button (translated from spanish, may not be exactly accurate)
> 
> ```
> Error "2147942402" while starting this command:
> "C:\Windows\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\SearchHost.exe" -ServerName:CortanaUI.AppXstmwaab17q5s3y22tp6apqz7a45vwv65.mca```
> ```

Thank you, might help me out here :sweat_smile: Probably because dependencies for that package are missing and that's causing delay. I'll have to take a look.
