### ISSUE TITLE
Remove bloatware

### ISSUE THREAD

**Issue by spouradrix** [teeotsa/windows-11-debloat#9]
Hi,

When I click remove bloatware, it takes a lot of time and a lot of tasks pop up in Powershell with the word initialized alongside each item.
Is it expected behavior? There is no message saying that it succeeded.

Thanks for the script,

**Comment by teeotsa** [comment]
Hey!

You mean something like this?
![image](https://user-images.githubusercontent.com/78772453/147838860-af6c4252-a69a-4ed3-846b-2fd0104a7ba7.png)

If so, then yes. It's expected.

Thank you!

**Comment by teeotsa** [comment]
No answer
